#!/usr/bin/env sh

SCSSIN="css/imports.scss"
CSSIN="css/style.css"
CSSOUT="css/style.min.css"

echo "Generating css from scss"
sass $SCSSIN $CSSIN

echo "Optimizing css using r.js"
node r.js -o cssIn=$CSSIN out=$CSSOUT optimizeCss=default
